### ISSUE TITLE
Swift 3 ?

### ISSUE THREAD

**Issue by hemantasapkota** [Lotame/LotameDMP-IOS#1]
We have a requirement to integrate this SDK. Any chance this is going to be converted to Swift 3 ?

Thanks
Hemanta

**Comment by irishfan99ko** [comment]
We don't have an ETA yet but we're working on getting the SDK up-to-date for swift 3. I'll reply here as soon as I know more.

**Comment by hemantasapkota** [comment]
Thanks for the prompt reply!!

**Comment by irishfan99ko** [comment]
Hello Hemanta, 

There's a new branch called feature/swift3.0 available now. Would you be willing to give it a try and provide us feedback please?

Thanks!

**Comment by hemantasapkota** [comment]
Sure thing. I also wanted to ask, if you have plans to support Carthage ( https://github.com/Carthage/Carthage ). 

Thanks

**Comment by hemantasapkota** [comment]
Hey guys, I tested out the swift3 branch. Works great.

Thanks.
