### ISSUE TITLE
Why is it not supported swift latest version?

### ISSUE THREAD

**Issue by pradipdesai** [Lotame/LotameDMP-IOS#10]
We are currently using swift 5.0 but the current version of LotameDMP is 3.0. Any chances to update this library for latest version of swift?

**Comment by irishfan99ko** [comment]
Apologies for the delay. There's a swift 5 compatible version in the feature/swift-5 branch.

**Comment by irishfan99ko** [comment]
We've merged the swift-5 branch to master.
