### ISSUE TITLE
Push latest changes to Cocoapods

### ISSUE THREAD

**Issue by asteiman** [Lotame/LotameDMP-IOS#11]
Hello,

The latest version in Cocoapods is 4.1.0, and with Swift 5 we are getting error in DMP.swift, line 77 `Static declarations are implicitly 'final'; use 'public' instead of 'open'`

I can see this was fixed in master, however the change is not pushed to Cocoapods, therefore we cannot get the fix.

Thanks,
Alan

**Comment by Sali0m** [comment]
Is there any news on when will the latest code version be pushed on cocoapods master repo?

**Comment by irishfan99ko** [comment]
Apologies for the delay. We've deployed a 4.2.0 version that should resolve this.
