### ISSUE TITLE
podspec minimum version iOS 14 for no reason

### ISSUE THREAD

**Issue by ebluehands** [Lotame/LotameDMP-IOS#15]
After the merge of the PR that handles `ATTrackingManager` from the `AppTrackingTransparency` framework the podspec was updated with a minimum requirement of `iOS 14`.

This change is not necessary since the use of the new framework was handled correctly with `if #available(iOS 14, *)`.

Also it's strange for a library to be that much restrictive with their minimum version iOS requirement since most apps run on `n` and `n-1` version.

Were there other reasons that I missed for this change or can we go back and lower the minimum required version ?

**Comment by irishfan99ko** [comment]
I reverted those changes. Sorry about that. I am still working through getting this new version compatible with cocoapods and carthage.
