### ISSUE TITLE
sendBehaviour with completion handler (objective-c)

### ISSUE THREAD

**Issue by hizamirashid** [Lotame/LotameDMP-IOS#2]
is there any completion handler for "function sendBehaviour" objective-c version?

**Comment by dandalf** [comment]
no it does not, but it is pretty simple to add that functionality. Standby for a new version with that functionality

**Comment by dandalf** [comment]
Hey @hizamirashid, the new version (4.0.0) has a sendBehaviorDataWithHandler method for objective-c callbacks.
