### ISSUE TITLE
LotameDMP v5.3.0 wasn't available as per your readme

### ISSUE THREAD

**Issue by dottam** [Lotame/LotameDMP-IOS#20]
`tag-5.3.0-swift-5.3.2-framework.zip` isn't available

The following link results in 404
https://github.com/Lotame/LotameDMP-IOS/blob/master/dist/tag-5.3.0-swift-5.3.2-framework.zip?raw=true 

`tag-5.2.0-swift-5.3.2-framework.zip` is an empty zip
https://github.com/Lotame/LotameDMP-IOS/blob/master/dist/tag-5.2.0-swift-5.3.2-framework.zip?raw=true

**Comment by irishfan99ko** [comment]
My apologies for that. I have updated the project to include the proper zip file, using swift version 5.9.2

**Comment by dottam** [comment]
The framework included in [tag-5.3.0-swift-5.9.2-framework.zip](https://github.com/Lotame/LotameDMP-IOS/blob/master/dist/tag-5.3.0-swift-5.9.2-framework.zip) doesn't include simulator slices

**Comment by irishfan99ko** [comment]
It doesn't look to me like the zip distribution ever included those. Can you point me to the best way to create them?

**Comment by dottam** [comment]
[tag-5.0.0-swift-5.0.1-framework.zip](https://github.com/Lotame/LotameDMP-IOS/blob/master/dist/tag-5.0.0-swift-5.0.1-framework.zip) includes simulator slice

Maybe you can consider distribute XCFramework

**Comment by irishfan99ko** [comment]
I have pushed a new version but I am not confident that it has what you're looking for.  We don't have in house iOS expertise so it will take a while for us to adjust here. It looks like something may have changed with the carthage cli capabilities that we were leveraging to generate the .zip file.

Any chance that Cocoapods is an option for you?

**Comment by dottam** [comment]
Cocoapods isn't an option for us as our apps use .NET MAUI
